<?php

namespace App\Console;

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Command\CompleteCommand;
use Symfony\Component\Console\Command\DumpCompletionCommand;
use Symfony\Component\Console\Command\HelpCommand;
use Symfony\Component\Console\Command\ListCommand;
use Symfony\Component\Console\Input\InputInterface;

class BaseApplication extends Application
{
    protected function registerCommands(): void
    {
        return;
//        return parent::registerCommands(); // TODO: Change the autogenerated stub
    }

//    protected function getDefaultCommands(): array
//    {
//        return [new ListCommand(), new HelpCommand(), new CompleteCommand(), new DumpCompletionCommand()];
//    }



}
